---
- name: Experiment with anchors and aliases
  hosts: localhost

  vars:
    - fruits: &types
        citrus:
          - orange
          - grapefruit
          - lime
        berries:
          - strawberry
          - raspberry
          - blackberry
          - blueberry
        melons:
          - watermelon
          - rockmelon
          - honeydew

  tasks:
    - name: Print out the list of fruits
      debug:
        var: 
          fruits:
            <<: *types
        #var: 
          #- fruits: 
              #<<: *types
              #stone_fruits:
                #- nectarine
                #- apricot
                #- peach
                #- cherry

- name: demonstrate the ability of an alias used with an anchor in an ewarlier play
  hosts: localhost

  vars:
    - fruits:
        <<: *types
        stone_fruits:
          - nectarine

  tasks:
    - name: Print out the list of fruits
      debug:
        var: fruits
        #var: 
          #fruits: 
            #<<: *types
            #stone_fruits:
              #- nectarine
              #- apricot
              #- peach
              #- cherry
            #melons:
              #- rockmelon
#
