---
- name: Unsave strings demo
  hosts: localhost

  vars_prompt:
    - name: unsafe_string
      propmpt: Provide some data
      private: False
      unsave: True

  tasks:
    - name: Create a file containing the user input
      copy: 
        content: "{{ unsafe_string }}"
        dest: /tmp/demofile.txt

